data <-read.table("household_power_consumption.txt",sep=";",skip=grep("1/2/2007", readLines("household_power_consumption.txt")),nrows=2880)
names(data)<-names(read.table("household_power_consumption.txt",sep=";",nrows=1,header=TRUE))
png(filename="plot3.png")
par(width=480)
par(height=480)
with(data,plot(Sub_metering_1,ylab="Energy sub metering",xaxt='n',type='l'))
with(data,lines(Sub_metering_2,col="red",type='l'))
with(data,lines(Sub_metering_3,col="blue",type='l'))
axis(1,at=c(1,1441,2881),labels=c('Thu','Fri','Sat'))
legend("topright",lty=c(1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_1","Sub_metering_1"))
dev.off()